### ISSUE TITLE
reference image project

### ISSUE THREAD

**Issue by zhangzhiru** [vg249/ECE5775_HybridImageProject#1]
Professor, 
We created a new project but we are not able to organize it , so whenever we run a our code or reference project we getting an error. I uploaded "HybridImage" project in github. Could you help us by giving us a reference Image project.
As openCV libraries are available in Vivado, We thought of using the openCV libraries available in Vivado to create the baseline design as openCV Image functions are synthesizable. Is it possible to install openCV in amdpool. If so, we will try creating cpp application which directly make use of openCV.

Thank you,
Vishnu G

**Comment by zhangzhiru** [comment]
If I understand you correctly, you are having trouble reading images in C++? Instead of using opencv, you can install the following png++ library under your local folder to read png files.  
http://www.nongnu.org/pngpp/

I believe that libpng is already installed on amdpool. You can directly use that as well.

Another (perhaps simpler) solution is to use a Python script to load in the image and dump out raw pixels into a big data file (or directly into a C arrays) that your C++ program can parse.

**Comment by vg249** [comment]
Professor, I am able to read the Image as Unsigned Char array.
But FFT Functions accepts input as Complex Numbers. I am not able to understand how i can convert  the unsigned char array to array complex numbers so that i can send them as input to FFT function.

**Comment by zhangzhiru** [comment]
So the question is not about reading images? Have you tried to simply feed the real values to the FFT?

Also, CImg is another useful C++ library you can try to install. It comes with some FFT routines, potentially useful for you to prototype the algorithm.
http://cimg.eu

**Comment by vg249** [comment]
Professor, We are getting unexpected result in multiplying gaussian mask with FFT result.
We tried several time with different approaches but could not figure out why the image is not getting filtered.
We calculated the gaussian values and saved it in the array and multiplied the FFT result of the image with gaussian matrix values.

"CimgExample.cpp" is the code file where we implemented the above mentioned design. We implemented the Low pass filter for the image. Could you please check the code and help us, if you feel we might be missing something?

**Comment by vg249** [comment]
/CImg/CimgExample.cpp

**Comment by zhangzhiru** [comment]
Please be more specific about (1) what is the problem, (2) how to reproduce it, and (3) the measures you have taken on debugging the issue. 

Are you seeing mismatches between Jeremy Kun's python program and your C program? If so, have you tried to print out the intermediate results to zero in on where the mismatches occur? Please make an effort to debug on your own. As I mentioned, I don't have much bandwidth to debug your program. If  necessary, I can ask my PhD student to help. But you will have to provide more detailed information first.

**Comment by vg249** [comment]
Sure Professor. We will check the mismatch between the Jeremy Kun's results and will get back to you on more detailed information.

**Comment by ng435** [comment]
Hi Professor,

We had some issues with the guassian filter implementation while converting the coefficients of the filter to complex data type. We were able to correct it and with the changes we made, we were able to finish the baseline design. The hybrid image generated was comparable with what we got using the python code. The final code is pushed on the github. Please find the hybrid images from our code and Jeremy Kun code as attachments. 
![jeremy_kun_marilyn-einstein](https://cloud.githubusercontent.com/assets/14019625/11435649/be63e694-94aa-11e5-95f2-c5cfbab0dfb2.png)
![c _marilyn-einstein](https://cloud.githubusercontent.com/assets/14019625/11435693/49ba37de-94ab-11e5-9dcc-4336ea487a9c.png)

Moving forward, we will be implementing the alternate design. Any suggestions from you will help us. 

Thank you.

**Comment by zhangzhiru** [comment]
Good progress. Let's try to get the synthesizable design working this week. Replacing the CImg FFT functions with Xilinx hls::fft functions would be a first step.
